introduction:
  title: Introduction
  changes: Change Log
gettingStarted:
  title: Getting started
  customGeneration: Artifacts custom generation
config: Setting up the configuration
unitTestDomainClasses:
  title: Creating unit tests for domain classes
  spockUnitTestDomainClasses: Creating unit tests with Spock
services: Creating services
unitTestServices:
  title: Creating unit tests for services
  spockUnitTestServices: Creating unit tests with Spock
logsServices: Creating logs for services
controllers: Creating controllers
unitTestControllers:
  title: Creating unit tests for controllers
  spockUnitTestControllers: Creating unit tests with Spock
views: Creating views
i18n: Creating i18n messages
